
stages:
  - build
  - deploy

.pypi_dependencies: &pypi_dependencies
  before_script:
    - pip install -U git+https://github.com/PyCQA/astroid@master#egg=astroid git+https://github.com/PyCQA/pylint@master#egg=pylint
    - pip install -U $(find requirements -name *.txt -print | sed -e 's/^/-r /' | tr '\n' ' ')

.git_dependencies: &git_dependencies
  before_script:
    - pip install -U git+https://github.com/Rapptz/discord.py@master#egg=discord.py[voice] git+https://github.com/PyCQA/astroid@master#egg=astroid git+https://github.com/PyCQA/pylint@master#egg=pylint
    - pip install -U $(find requirements -name *.txt -print | sed -e 's/^/-r /' | tr '\n' ' ')

.run_tests: &run_tests
  script:
    - PYTHONPATH="$(pwd)" pytest -vs --cov=jishaku --cov-report term-missing:skip-covered
    - flake8 .
    - pylint -j "$(nproc)" jishaku
    - isort . --check-only --recursive
    - python ./setup.py sdist bdist_egg bdist_wheel
    - rm -rf jishaku
    - find dist -name *.whl -exec pip install '{}' +
    - pytest -vs
    - cd docs && make html

alpine 3.6 pypi:
  stage: build
  image: gorialis/discord.py:3.6-alpine-master
  <<: *pypi_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

buster 3.6 pypi:
  stage: build
  image: gorialis/discord.py:3.6-buster-master
  <<: *pypi_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

alpine 3.7 pypi:
  stage: build
  image: gorialis/discord.py:3.7-alpine-master
  <<: *pypi_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

buster 3.7 pypi:
  stage: build
  image: gorialis/discord.py:3.7-buster-master
  <<: *pypi_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

alpine 3.8 pypi:
  stage: build
  image: gorialis/discord.py:3.8-alpine-master
  <<: *pypi_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

buster 3.8 pypi:
  stage: build
  image: gorialis/discord.py:3.8-buster-master
  <<: *pypi_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

alpine 3.6 git:
  stage: build
  image: gorialis/discord.py:3.6-alpine-master
  <<: *git_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

buster 3.6 git:
  stage: build
  image: gorialis/discord.py:3.6-buster-master
  <<: *git_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

alpine 3.7 git:
  stage: build
  image: gorialis/discord.py:3.7-alpine-master
  <<: *git_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

buster 3.7 git:
  stage: build
  image: gorialis/discord.py:3.7-buster-master
  <<: *git_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

alpine 3.8 git:
  stage: build
  image: gorialis/discord.py:3.8-alpine-master
  <<: *git_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

buster 3.8 git:
  stage: build
  image: gorialis/discord.py:3.8-buster-master
  <<: *git_dependencies
  <<: *run_tests
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

pages:
  stage: deploy
  image: alpine:latest
  script:
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: deploy
  image: gorialis/discord.py:3.8-alpine-master
  before_script:
    - pip install -U twine
    - ls dist
    - export TWINE_USERNAME="$(echo -e $TWINE_USERNAME)"
    - export TWINE_PASSWORD="$(echo -e $TWINE_PASSWORD)"
  script:
    - twine upload dist/*
  artifacts:
    paths:
      - dist
  only:
    - tags@Gorialis/jishaku
