
build: off

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

install:
  - ps: if (-not(Test-Path($env:PYTHON))) { & _appveyor\install.ps1 }

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%CMD_IN_ENV% SET PYTHONPATH=%CD%;%PYTHONPATH%"

  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "python -m pip install -U pip setuptools wheel"
  - "%CMD_IN_ENV% pip install -U -r requirements/_.txt -r requirements/docs.txt -r requirements/procinfo.txt -r requirements/test.txt -r requirements/voice.txt"
  - "%CMD_IN_ENV% pip install -U git+https://github.com/Rapptz/discord.py@master#egg=discord.py[voice] git+https://github.com/PyCQA/astroid"

test_script:
  - "%CMD_IN_ENV% pytest -vs --cov=jishaku --cov-report term-missing:skip-covered"
  - "%CMD_IN_ENV% flake8 ."
  - "%CMD_IN_ENV% pylint jishaku"
  - "%CMD_IN_ENV% isort . --check-only --recursive"

after_test:
  - "%CMD_IN_ENV% python setup.py sdist bdist_egg bdist_wheel"

artifacts:
  - path: dist\*
